import type { Metadata } from "next";

import { Toaster } from "@/components/ui/sonner"
import "./globals.css";
import Navbar from "../components/Navbar/Navbar";
import Container from "../components/global/container";  
import Footer from "../components/footer/Footer";
import { ThemeProvider } from "../components/theme-provider";
import { ClerkProvider } from "@clerk/nextjs"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
   <ClerkProvider>
       <html lang="en" suppressHydrationWarning>
            <body className="min-h-screen flex flex-col antialiased">

            <ThemeProvider
                attribute="class"
                defaultTheme="system"
                enableSystem
                disableTransitionOnChange>
                <Navbar/>

                <main className="flex-1">
                  <Container className="pt-12">
                    {children}
                    <Toaster />
                  </Container>
                </main>

                <Footer />
            </ThemeProvider>
              
            </body>
        </html>
   </ClerkProvider>
  );
}
