import type { Metadata } from "next";

import { Toaster } from "@/components/ui/sonner"
import "./globals.css";
import Navbar from "../components/Navbar/Navbar";
import Container from "../components/global/container";  
import { ThemeProvider } from "../components/theme-provider";
import { ClerkProvider } from "@clerk/nextjs"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
   <ClerkProvider>
       <html lang="en" suppressHydrationWarning>
            <body>

            <ThemeProvider
                attribute="class"
                defaultTheme="system"
                enableSystem
                disableTransitionOnChange>
                <Navbar/>

            <Container className="pt-12">
              
              {children}
              <Toaster />
            </Container>

            </ThemeProvider>
              
              
            </body>
        </html>
   </ClerkProvider>
  );
}
